name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - java
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - pixiedust
    - seaborn
    - japanize_matplotlib
